# Generated by Django 3.2.25 on 2024-03-22 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Public',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=3000, verbose_name='description')),
                ('img_files', models.ImageField(upload_to='avatars', verbose_name='media')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='data_at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_users', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_public', to='webapp.public', verbose_name='public')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='like_users', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=3000, verbose_name='comment')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='data at')),
                ('public', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_public', to='webapp.public', verbose_name='public')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='comment_user', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
